# Generated by Django 5.1.3 on 2024-12-11 07:12

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[286, 180], upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearapp.itemcategory', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='maincategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearapp.maincategory', verbose_name='name'),
        ),
    ]
