# Generated by Django 5.1.3 on 2024-12-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0002_item_image_item_info_alter_item_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearapp.itemcategory', verbose_name='Sub category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
