# Generated by Django 5.1.3 on 2024-12-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0005_maincategory_user_storage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date_start', models.DateField()),
                ('date_emd', models.DateField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missiont_item', to='gearapp.mission')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_item_strorageitem', to='gearapp.missionitem')),
            ],
        ),
    ]
