# Generated by Django 5.1.3 on 2024-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0007_mission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='date_emd',
        ),
        migrations.AddField(
            model_name='mission',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
