# Generated by Django 5.1.3 on 2024-12-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0008_remove_mission_date_emd_mission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mission_item_item', to='gearapp.item'),
            preserve_default=False,
        ),
    ]
