# Generated by Django 5.1.4 on 2024-12-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0009_missionitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lease_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
